### ISSUE TITLE
Time alive global leaderboard is incorrect

### ISSUE THREAD

**Issue by jespertheend** [jespertheend/splix#118]
Many of the entries are displayed as 00:00:00 right now.
And the highest player has a time of 203:29:30, which is impossible considering that the global leaderboard has only been released for a couple of hours.

**Comment by abhishek276533** [comment]
Its due to the logic miss. You are adding `duration` to `#rankingFirstSeconds` inside `#incrementRankingFirstSeconds()` which should be first converted to seconds, and then it should get added.
If we do this, we don't have to specifically convert the time inside the `#permanentlyDie()` function.

Lmk if im missing some edge case over with this logic

The other approach would be to leave the above logic as it is and, inside `getGlobalLeaderboardScore()` convert the time again to seconds and send it back.

Happy to raise PR for this :)
