### ISSUE TITLE
game server: Undo player death bug

### ISSUE THREAD

**Issue by abhishek276533** [jespertheend/splix#27]
### Issue Summary
After the recent changes for `UNDO_PLAYER_DIE` allowing the players to go over their trails

### Steps to Reproduce
1. Spawn the player
2. Make a trail and pause before your own trail
3. Move the player towards the trail and pause which makes it like a `fake-hit` and now quickly jump over the trail

### Actual Results
-The player is able to move over their trail for 2-3 blocks 
![image-1](https://github.com/jespertheend/splix/assets/62441572/3de0dc60-1f39-48c4-a811-8ea15eb25ff8)
![image-2](https://github.com/jespertheend/splix/assets/62441572/703f4bd6-e49f-4d1a-b2f3-2c5c4d12d3fd)

### Expected Results
-The player should die

### Describe the fix
- Could be related to #24

**Comment by jespertheend** [comment]
I think the problem here is that you are able to create multiple trail vertices when pausing, even though those vertices all lie on the same line. Ideally it should check if a new vertex lies on the same line and only add it if that's not the case.
`drainMovementQueue` now contains `this.#trailVertices.push`, but that's where a check should be added.

**Comment by abhishek276533** [comment]
I already tried adding that and it's still not killing the player. 
```js
if (this.isGeneratingTrail && !this.pointIsInTrail(this.#currentPosition)) {
	this.#trailVertices.push(firstItem.desiredPosition.clone());
}
```
I think it's due to the time constraint that you've put When I set it to `166` it was working fine. But it should depend on player's `Ping`
```js
if (this.#lastDeathState) {
	const dt = performance.now() - this.#lastDeathState.dieTime;
	if (dt > MAX_UNDO_EVENT_TIME) {
		this.#permanentlyDie();
	}
}
```

**Comment by jespertheend** [comment]
`MAX_UNDO_EVENT_TIME` is there to prevent clients from undoing events that lie ridiculously far in the past. Making that depend on the actual ping of the client would allow players to cheat a lot when they have a very high ping.

But I think you're right, this sounds like the problem is that the player is undoing deaths when pausing, which shouldn't be possible.

**Comment by jespertheend** [comment]
I was also able to reproduce this bug near the wall, which causes the server to crash. I'll investigate.

**Comment by jespertheend** [comment]
Seems like I simply forgot to implement some logic in `undoRecentEvents()`, although the check in `drainMovementQueue()` might be needed as well

**Comment by jespertheend** [comment]
Should be fixed now, the check for unnecessary trail vertices didn't seem to make much of a difference, but I've created #33 because it might make things more robust anyway.
